Feat/crud rooms rentals services
maironald/demo-rental-house pull request #2
Opened 2024-01-12 06:58 UTC by maironald

# Description

- CRUD features in rooms
- CRUD features in rentals
- CRUD features in services

# Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings

# UI 

- Table rooms:

![Screenshot from 2024-01-12 13-43-20](https://github.com/maironald/demo-rental-house/assets/154109143/1cf5ff1f-0eb9-4a85-9004-19963fc03f07)

- Table renters:

![Screenshot from 2024-01-12 13-54-20](https://github.com/maironald/demo-rental-house/assets/154109143/91585f97-7da2-45bf-b478-db1f703ed6df)

- Table services:

![Screenshot from 2024-01-12 13-55-43](https://github.com/maironald/demo-rental-house/assets/154109143/5624fb43-a12e-4557-8459-0672e37dd722)

- UI Dashboard

![Screenshot from 2024-01-12 13-56-31](https://github.com/maironald/demo-rental-house/assets/154109143/e91180e5-978c-4e4a-92de-874812352593)

2024-01-12 10:53 UTC, jacky-le-goldenowl requested changes

2024-01-12 10:53 UTC, jacky-le-goldenowl commented on app/controllers/renters_controller.rb
> +    @default_rooms = current_user.rooms.select { |room| room.renter_id.nil? }
Same above

2024-01-12 10:53 UTC, jacky-le-goldenowl commented on app/controllers/renters_controller.rb
> +    @room_info = Room.find_by(id: renter_params[:rooms_attributes]['0'][:id])
renter có nhiều phòng à?
Chỗ này cần làm lại

2024-01-12 10:53 UTC, jacky-le-goldenowl commented on app/controllers/renters_controller.rb
> +      Room.where(id: @room_info.id).update(renter_id: @renter.id)
Làm lại nguyên controller này

2024-01-12 10:53 UTC, jacky-le-goldenowl commented on app/controllers/timesheets_controller.rb
> +  # The before_action is used to avoid duplicating the same code in multiple places and ensure that the necessary setup is done consistently before executing those actions (4 actions: show, edit, upd
remove this

2024-01-12 10:53 UTC, jacky-le-goldenowl commented on app/javascript/controllers/hello_controller.js
> +    // debugger;
remove this line

2024-01-12 10:53 UTC, jacky-le-goldenowl commented on app/javascript/controllers/shared/flash_controller.js
> +    // Set display to "none" or remove the element from the DOM
remove this line

2024-01-12 10:53 UTC, jacky-le-goldenowl commented on app/javascript/controllers/shared/flash_controller.js
> +    // Alternatively, if you want to remove the element from the DOM
remove this 2 lines

2024-01-12 10:53 UTC, jacky-le-goldenowl commented on app/javascript/pack/custom.js
> +document.addEventListener('turbolinks:load', function(){
Move all code from pack to stimulus controller

2024-01-12 10:53 UTC, jacky-le-goldenowl commented on app/models/room.rb
> +  belongs_to :renter, optional: true
Should use has_one

2024-01-12 10:53 UTC, jacky-le-goldenowl commented on app/models/room_service.rb
> +class RoomsService < ApplicationRecord
Set name model wrong

2024-01-12 10:53 UTC, jacky-le-goldenowl commented on app/models/service.rb
> +  has_many :rooms_services, dependent: :destroy, class_name: 'RoomsService'
remove this: ` class_name: 'RoomsService'`

2024-01-12 10:53 UTC, jacky-le-goldenowl commented on app/models/user.rb
>      # create a new user with provider and uid followed by google to add to the database.
Remove comment

2024-01-12 10:53 UTC, jacky-le-goldenowl commented on app/views/layouts/application.html.erb
> +    <%= javascript_include_tag '/pack/custom', "data-turbo-track": "reload", defer: true %>
Remove this line, We just use stimulus to mange javascript code

2024-01-12 10:53 UTC, jacky-le-goldenowl commented on app/views/renters/_form.html.erb
> + <%= f.simple_fields_for :rooms do |room_fields| %>
I think we do not add room to renter when create

2024-01-12 10:53 UTC, jacky-le-goldenowl commented on app/views/renters/index.html.erb
> +                style="background-color: rgb(232, 247, 253); display: flex; flex-direction: column; justify-content: space-around; width: 100%; flex-wrap: wrap;">
Dont use style inline. Set class name and move all css style to scss file

2024-01-12 10:53 UTC, jacky-le-goldenowl commented on app/views/renters/index.html.erb
> +                                          <a href="#"><svg class="w-3 h-3 ms-1.5" aria-hidden="true"
Move svg to svg image and call image with vite_image_tag

2024-01-12 10:53 UTC, jacky-le-goldenowl commented on app/views/renters/index.html.erb
> +                                      <%= renter.gender? ? "Nam" : "Nữ"%>
Should use gender type string

2024-01-12 10:53 UTC, jacky-le-goldenowl commented on config/routes.rb
> +  resource :users do
resource or resources ?

2024-01-14 17:27 UTC, maironald commented
I have changed:
- The room-controller, room-service
- Change css to scss
- Change the svg to image_tag
- Change javascript to the stimulus

2024-01-15 05:15 UTC, merged